### ISSUE TITLE
The layout operation overrides the style height of my node (and crashes if height is not defined)

### ISSUE THREAD

**Issue by charleshetier** [retejs/auto-arrange-plugin#36]
Rete library is wonderfull, I have however a little issue on a quite specific case:

As my node content is dynamic, I would like the height of my nodes to also be dynamic.

* If no height  as number property on my node is defined, the layout operation is crashing 
* If I don't bind the height style value in my vue3 node component, it is overridden by the layout operation

Would it be possible to prevent the layout operation to set the height style onto the node content element ?

as an example,

Beginning of my node definition using vue3 component:
```html
<template>
  <div class="node" :class="{ selected: data.selected }" :style="nodeStyles()">
...
```
nodeStyleFunction implementation:
```typescript
function nodeStyles() {
      return {
        width: Number.isFinite(this.data.width) ? `${this.data.width}px` : '',
        // height: Number.isFinite(this.data.height) ? `${this.data.height}px` : ''
      }
    }
```

invoking `await arrange.layout({ applier: new StandardApplier() });` sets manually the style.height into my html component **(oustide of the life vuejs cycle)**

Am I missing something ?

Thank you

Charles

**Comment by Ni55aN** [comment]
> the layout operation is crashing

the plugin (-> elk.js) requires nodes to have height/width properties defined (it doesn't retrieve sizes from the DOM for performance/concurrency reasons)

Solution 1: Calculate the height/width based on the inputs/outputs/controls.
Solution 1: Sync height/width using `getBoundingClientRect`, but it won't work with 3D area plugin.

> it is overridden by the layout operation

`area.resize`, which is called by `layout` (applier), changes the `style` attribute because in some cases elk.js can recalculate sizes, for example for parent nodes.

https://github.com/retejs/auto-arrange-plugin/blob/701f011514752785be948f6e5ad08e1ec85e5f9d/src/appliers/list/standard.ts#L18-L20

Solution: If you don't need this behavior, you can extend `StandardApplier` and override `resizeNode`
